trigger:
  branches:
    include:
      - main  # Trigger on push to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'banking'  # Docker image name
  registry: '<your-acr-name>.azurecr.io'
  serviceConnection: '<your-service-connection>'
  appServiceName: '<your-app-service-name>'
  resourceGroupName: '<your-resource-group>'
  imageTag: '$(registry)/$(imageName):$(Build.BuildId)'  

steps:

  - task: Checkout@1
    displayName: 'Checkout repository'

  - task: Docker@2
    displayName: 'Login to Azure Container Registry (ACR)'
    inputs:
      command: login
      containerRegistry: $(serviceConnection)

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      dockerfile: '**/docker-compose.yml'  # Path to the Dockerfile
      tags: $(imageTag)

  - task: Docker@2
    displayName: 'Push Docker image to ACR'
    inputs:
      command: push
      tags: $(imageTag)

  - task: AzureWebAppContainer@2
    displayName: 'Deploy Docker image to Azure App Service'
    inputs:
      azureSubscription: $(serviceConnection)
      appName: $(appServiceName)
      resourceGroupName: $(resourceGroupName)
      dockerRegistryConnection: $(serviceConnection)
      imageName: $(imageTag)
      configurationStrings: '-DOCKER_CUSTOM_IMAGE_NAME=$(imageTag)'
      containerCommand: 'docker compose up'
